window:
  padding:
    x: 12
    y: 12
  decorations: full
  opacity: 0.95
  dynamic_title: true
  startup_mode: Windowed

font:
  normal:
    family: "JetBrainsMono Nerd Font"
    style: Regular
  bold:
    family: "JetBrainsMono Nerd Font"
    style: Bold
  italic:
    family: "JetBrainsMono Nerd Font"
    style: Italic
  size: 11.5
  offset:
    x: 0
    y: 1

colors:
  primary:
    background: '0x1e1e2e'
    foreground: '0xcdd6f4'

  normal:
    black:   '0x1e1e2e'
    red:     '0xf38ba8'
    green:   '0xa6e3a1'
    yellow:  '0xf9e2af'
    blue:    '0x89b4fa'
    magenta: '0xf5c2e7'
    cyan:    '0x94e2d5'
    white:   '0xcdd6f4'

  bright:
    black:   '0x585b70'
    red:     '0xf38ba8'
    green:   '0xa6e3a1'
    yellow:  '0xf9e2af'
    blue:    '0x89b4fa'
    magenta: '0xf5c2e7'
    cyan:    '0x94e2d5'
    white:   '0xffffff'

cursor:
  style: Beam
  blink: true

selection:
  save_to_clipboard: true

shell:
  program: /bin/bash
