[window]
padding = { x = 12, y = 12 }
decorations = "full"
opacity = 0.95
startup_mode = "Windowed"
dynamic_title = true

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 11.5
offset = { x = 0, y = 1 }

[cursor]
style = { shape = "Beam", blinking = "Always" }

[colors.primary]
background = "#1e1e2e"
foreground = "#cdd6f4"

[colors.normal]
black = "#1e1e2e"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#cdd6f4"

[colors.bright]
black = "#585b70"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#ffffff"

[selection]
save_to_clipboard = true

[terminal]

[terminal.shell]
program = "/usr/bin/zsh"
args = ["--login"]

#[terminal.shell]
#program = "/usr/bin/zsh"
#args = ["--login"]
